name: Covalent CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npx nx run-many --target=lint --all

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - run: npx nx run-many --target=test --all

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - run: npx nx run-many --target=build--all
