name: Covalent CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - run: echo "${{ github.event.head_commit.message }}" | npx commitlint
      - run: npx nx prettier:check
      - run: npx nx affected --target=lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - run: npx nx affected --target=test --base=origin/main --head=HEAD --with-deps

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - run: npx nx affected --target=build --base=origin/main --head=HEAD --with-deps
