name: Deploy GitHub Page
on:
  push:
    branches:
      - main
    paths:
      - 'libs/components/**'
      - 'libs/icons/**'
      - 'libs/tokens/**'
jobs:
  deploy-github-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build story book artifacts
        run: npm run storybook:build

      - name: Upload storybook artifact  

      - uses: actions/upload-artifact@v3
        with:
          name: storybook
          path: storybook-static/
